name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: |
            linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/salvo-pcywwxzx:latest
    - name: Trigger Webhook
      uses: peter-evans/http-request-action@v1
      with:
        url: 'http://eromanga.top:9000/api/stacks/webhooks/8d0f20cc-7549-4db2-bef0-2ce566762895'
        method: POST